x-aws-cluster: "Twilio-Stripe-Node"
x-aws-vpc: "vpc-7bb9021e"
version: '2'
services:
  web:
    image: 686878367233.dkr.ecr.us-west-2.amazonaws.com/docker-composetest:latest
    build:
      context: .
    ports:
      - "8080:8080"
