x-aws-vpc: "vpc-025fae40153b99f96"
version: '2'
services:
  web:
    image: 686878367233.dkr.ecr.us-west-2.amazonaws.com/docker-composetest:latest
    build:
      context: .
    ports:
      - "8080:8080"
